### ISSUE TITLE
Anyone interested on mutiple echoes using the same "device name"?

### ISSUE THREAD

**Issue by Barabba11** [datech/node-red-contrib-amazon-echo#101]
Hi mates, unfortunately the author refused to implement this but I'm not loosing the hope someone may help me to find the way. I'm sure there is a common situation to place home more Echoes and say simple commands like "Alexa switch off the lights" or "close curtains" instead of "Alexa switch off the living room lights", which is one floor lower then bedroom.. too far to use one Echo only.

We can't use the same device name, but if we can filter the device somehow, only one Echo will recognize and manage it, this is my goal. To filter it we can introduce another parameter in device's option menu, where we can type the IP only of the echo device we want to allow manage it, or its MAC address. I suppose it is not too difficult to implement, the IP source address of Echo should be easly accessible inside the script and we simply avoid to proceed if it doesn't match the device parameter, few lines should be enough to do the job.
My experience with javascript is too few to do that, and I'm afraid to loose too many hours doing something an expert can do in 5 minutes.. 
Thank you a lot for you kind answers!

**Comment by slopsjon** [comment]
Can't you use a Routine in the Alexa app or create a group.

**Comment by Barabba11** [comment]
thanks for your reply, can you please explain better your idea?
The big problem I'm facing is that all Echoes are recognizing all devices, and if I give the same name it will be a big confusion which Echo will operate to that device and what exact device will be driven if it has the same name?
Honestly I see only the IP (or MAC) filter for every device.. anyone is interested? I suppose it's a common issue, to use same names in different Echos

**Comment by Barabba11** [comment]
Hi everyone, I really hope somebody can help me to edit code. If I'm not wrong the change will not be difficult to do, probably just few line.. but I'm too newbie to javascript to do this myself ((
Thank you a lot for your kind help

**Comment by slopsjon** [comment]
I have three lights in the front of my flat. The bathroom light, the hall light and the kitchen light. I tell Alexa to switch of Front Lights, and Alexa switches of all three lights from what ever Echo I speak to. Alexa does this because in the Alexa app I created a group and put the three light devices into this group and called the group Front Lights. If you go into the Alexa app under devices it asks do you want to create a group, put all your lights into a group give it a name like All Lights and then when you are upstairs you just say Alexa turn All Lights off.  

If you want to do a sequence of things then you can you use routines (with groups) like when I go to bed I say Alexa Good Night and Alexa will say something, turn my light off  reduce the volume on my bedroom Alexa, and then play some music or sound for one hour to help me sleep. I also use Node-Red with this and can turn on Shuffle and/or repeat and randomly select what will play i.e Ocean Sounds.

So if I am understanding your problem correctly you need to read about Groups and Routines in the Alexa app. Assuming they are available in your country.

**Comment by Barabba11** [comment]
Thanks for answer, unfortunately I don't need to give a command which turn on/off different devices but I need to use the same name to turn on or off a particular device. Imagine you have 2 floors and 2 Echos, you have shutters and you want to close them down, imagine you have one wifi where all devices can recongnize all devices, now you have to give 2 different commants to distinguish the sutters on first floor: "Alexa turn off shutters first floor", if you say "Alexa turn off shutters" she may reply she doesn't understand or by chance she will drive the wrong ones. If we can assign a device to a specific Echo IP then only that Echo will recognize it and manage it, you can go in both floors and say just "alexa switch off shutters" and she will drive the right ones, only.

**Comment by dermm** [comment]
Hi,
if you put the echo together with lights in a room/group, then you can use exact this echo with "Switch off lights". This only works if you don't have a device or group called lights. Works for me without problems also with sockets.

Such commands are then assigned to the group the echo is in.

**Comment by Barabba11** [comment]
Thank you for reply, sorry mat I can't understand you right, can you please write in other words, maybe one example will bright your idea, thanks.
It sounds to me you have a group of lights that you command all together with "Alexa switch the lights on", to do that you associated all devices in a group, in the Alexa account.
My request is completely different, I wrote it again in the previous post, may ou read it accurately? Thank you

**Comment by dermm** [comment]
Groups can be created in the Alexa App.
If you assign an echo to exactly one group, texts like "turn on light" will be assigned to all lights of this group. 

If you have 3x echoes. 
Group Kitchen
-Light 1
-Light 2
Group living room
- Light 10
- Light 11
- Light 12
Group bedroom
- Light 20

When you say "turn on light" to the echo in the living room, lights 10, 11 and 12 are switched on.
When you say "switch on light" to the echo in the kitchen, lights 1 and 2 are switched on.
This works like the preferred loudspeaker.

Is this more understandable?

It also goes "turn off the light in the bedroom" and the group bedroom is controlled from each echo.

**Comment by wongnam** [comment]
@dermm Agree your way is officially supported by Alexa only for lights. however, other things such as fan curtains and so on are not supported.

**Comment by Barabba11** [comment]
Hi mates, thanks for explaining, it was exactly how I got it and I confirm this is not what I was meaning. I understand that the title of topic may put us in trouble, there could be 2 different meanings:
1) one name to drive serveral devices - what you got
2) the same name used on different echoes, but able to drive different devices - What I mean.

The solutions aren't compatible, it's a different nature issues. I wrote in detail and gave some concrete examples, but probably you didn't read them.

**Comment by aseedorf** [comment]
This is possible without knowing JS:
1. create a device
2. catch the device-id by binding alexa-hub to debug (set debug to complete msg object=
(you will finde the device-id under deviceid)
3. create a switch and connect it to alexa-hub
4. configure switch: Property: meta.insert.details.ip
== [IP of alexa device]
5. do this for all alexa devices
6. connect new switches, which catch the deviceid and if needed use "change-node" to send correct payload
7. route this payload to your physical device

this has to be done for every device. the alexa-device is then only used to create the name (e.g. lamp, radio, tv).
the switch-logic routes the command without using the alexa-device to your physical device.
but be warned: its a lot of work and if the device

**Comment by Barabba11** [comment]
Thank you for your kind suggestion, there are some infos which are not clear for me:
4. the concept is good, filter messages from hub to devices according the IP address, this may block also the search for new devices.. which is actually the main goal. But why use a switch for each device? it's enough one, once the message is filtered can be sent to all devices that should be recognized by that Echo IP...

point 6 I can't understand, connect new switches where? catch the deviceid what for? , use change node for which reason? You probably have to explain me better the flow you want to realize ))
thanks for infos :)

**Comment by aseedorf** [comment]
to point 4:
i was not clear, as i wrote "for all alexa devices". i meant: alle physical alexa devices like an echo dot or echo show...
so:
you say: alexa, turn lights on
what happens: a message-object is sent, which includes the ip from which alex-device the command was sent.
now you can identify the alex-device by ip to switch lights on/off for example on first floor, because the ip corresponds to an echo-dot on the first floor.
this has to be done for each device corresponding to the location, so for every physical device (e.g. echo dot) you have to create a switch.

point 6 may be obsolete. if you just control only lights, there is no need for any further switch. But if you also want to control a curtain or what ever, you hae to filter out, what to control.

<img width="579" alt="Bildschirmfoto 2020-07-24 um 10 29 18" src="https://user-images.githubusercontent.com/2181572/88374156-8eefec00-cd99-11ea-9861-97412b9bbb32.png">
<img width="583" alt="Bildschirmfoto 2020-07-24 um 10 33 41" src="https://user-images.githubusercontent.com/2181572/88374172-9616fa00-cd99-11ea-8edd-9296df6ebec8.png">
<img width="1085" alt="Bildschirmfoto 2020-07-24 um 10 35 22" src="https://user-images.githubusercontent.com/2181572/88374197-9e6f3500-cd99-11ea-902e-668ef973b2f5.png">

i hope, that helps

**Comment by Barabba11** [comment]
thank you for your explanation and including pictures :)
It's itneresting to develope the discussion with you, I hope you are interested too to develope it. 

My main goal is to use the same names for different echos, for example "alexa turn the curtains off" (as unfortunately we can't see "Alexa close down the curtains, we're dealing with a bulb device and Alexa get smarter recently, it wull not accept ambigous commands) will turn down the curtains on the floor there that Echo will be. On another floor there is another Echo, and also a Curtains device. 
To achieve this goal the Echo should discover *only* devices that he has to control, looking your scheme there is not filter between hub and devices as I expected you place to filter out the IP address, and even if you did I was curious if that will be enough to filter out the device recognition too.. I don't think so, unfortunately. 

Reasoning about your scheme you may reduce the numbers of switches using the Alexa Devices to filter the device, simply use the switch node "get echo device" and connect to it the output of all Alexa devices, then up true or down false.. 

Anyway, using the same name and let both Echo recognize 2 devices with the same name create unexpected result. May you please try to filter the packet between hub and device? Let's see if it stops recognizing devices, if so it's bingo. 
Unfortunately now I'm far and I can't test it.

PS: if it will not me successful as I guess (the wires on Node Red are one way only, on recognition I suppose the HUB ask how many devices are ready, but devices acan't reply back to HUB, so the module simply look how many devices are located on the flow, and wires are not important) the ony solution I see is to place devices for first Echo and recognize them from first Echo only, cut them manually from the flow.js file, add devices for the second Echo, discover from the second Echo only, paste the ones I cut before and deactivate the recognition.
Unfortunately it's not very easy and it doesn't let simply add new devices in future.
There will be amazing to have for each device the chance to specify the IP of the Echo it should deal with only

**Comment by Barabba11** [comment]
@aseedorf do you share what I wrote? 
Thanks

**Comment by datech** [comment]
Alexa groups can be used. More info here: #197
