### ISSUE TITLE
Echo doesn't find devices in standard Homematic

### ISSUE THREAD

**Issue by czacherl** [datech/node-red-contrib-amazon-echo#125]
##### SUMMARY
I am running a homematic ccu3 in the standard installation without root access.
I have the latest version of redmatic installed and have added the pallette for Alexa. As with others before, port 80 is showing an error on the Alexa Hub. Changing the port to a selection over 1024 just helps in showing "online" in the mode. Though, Alexa doesn't find the device connected.
Even with port forwarding, Alexa doesn't find any devices.

Addition: After changing the port via forwarding, I cannot access the UI of the homematic anymore.

##### ECHO DEVICES
Echo Plus 2nd generation 

##### MODULE VERSION
```paste below
Redmatic v5.3.3
```

**Comment by Barabba11** [comment]
the reason was discussed dozen of times, probably the author should make it more evident in the readme file to help people don't loose too much time around it. If you are using Raspberry or probably other Linux system the module can't use a port lower than 1024, this is why you need to MAP the port you chose to port 80 by linux command line. Alexa will comunicate only with devices who are able to communicate with port 80, chosing other ports will not help. You just need few lines to map the port

**Comment by czacherl** [comment]
@Barabba11, thanks for your reply.
I am using the original unrooted Homematic CCU3 like it had been provided by the manufacturer. I can install additional software on it, like redmatic.
As you said, I have found all the port mapping advice, even in the troubleshooting section on the github WIKI. So, I have tried to forward the ports with
'ssh root@'
to e.g. port 4502 according to:
`iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 4502`
I cannot use sudo on the homematic command line, it's a read only file system, it says. Though,
'iptables -t nat -L'
shows the right entry in the forwarding table (until I reboot the homematic device, which makes it loose the entry).
Anyways, it doesn't work. After I have entered the port forwarding and restarted the redmatic, my Alexa still does not find the device I have created in redmatic.
Just to be complete: I have created an Amazon Hub with port 4502 and added a connected Device with the name 'Test Device', including a debug node.

I even had opened the port 4502 in my rooter. As I thought, that might help. It didn't.

Is there anything I forgot or don't know to do after deploying the setup in redmatic after initializing port forwarding? Did I do something wrong?
Is there anything else you can think of, that I might have missed doing?

**Comment by Barabba11** [comment]
Sorry I don't know what Homematic is, what I can say you that Alexa look for devices in the same LAN and on their port 80 only, so this module should listen somehow the port 80 of your device. The router is a border device and it will not help anyway.
Maybe you have the port 80 opened already by something else, which you need to kill or move to make it free. If you can't I strongly suggest you to move to another hardware, buy a cheap raspberry it worth the cost instead of many hours of workaround

**Comment by czacherl** [comment]
Homematic is a Smart Home Device provider which offers a home automation system, based on a ccu3.
The ccu3 on delivery offers a UI for managing the devices.
After port forwarding, I can no longer access that UI. It seems, it is using the port 80 for presentation in the browser.
I have checked the netstat on the ccu and it says, my computer is the one using the port 80 on the browser.
I would not know what else might be using the port 80.
Could you please tell me, if at least, I am doing the forwarding right? If so, I can then just give up my efforts and stay with the alexa skill I have bought to work with my smart home stuff.
Thanks in advance.

**Comment by Michael-Red** [comment]
The following commands are valid to redirect routing to port 80 for device detection:
iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT 
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080

Please detect devices with Alexa

To return to normal operation for Homematic UI after detecting devices 
iptables -F 
iptables -F -t nat

This will reset all temporary rules

Have fun.

**Comment by czacherl** [comment]
Thank you @Michael-Red for that Input.
Anyways, it didn't work :-(
I have added the rules as you provided them and changed the Amazon Echo Hub port to 8080, also tried it on 80 and have tried it on 4502 like I did in the beginning.
Still, Alexa does not recognize the `Test`device, that I have installed in my flow:
`[
    {
        "id": "5ab42159.fb97d",
        "type": "tab",
        "label": "Wohnzimmer",
        "disabled": false,
        "info": ""
    },
    {
        "id": "9b105139.7da45",
        "type": "amazon-echo-hub",
        "z": "5ab42159.fb97d",
        "port": "8080",
        "processinput": "2",
        "discovery": true,
        "x": 280,
        "y": 240,
        "wires": [
            [
                "f0e0711f.99b51"
            ]
        ]
    },
    {
        "id": "f0e0711f.99b51",
        "type": "amazon-echo-device",
        "z": "5ab42159.fb97d",
        "name": "Test",
        "topic": "",
        "x": 490,
        "y": 240,
        "wires": [
            [
                "3207ec82.8ae174"
            ]
        ]
    },
    {
        "id": "3207ec82.8ae174",
        "type": "debug",
        "z": "5ab42159.fb97d",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 700,
        "y": 260,
        "wires": []
    }
]`

I have tried to find the device for over an hour, just to be sure, there is no delay after the deployment.

I think this just does not work for me. If you have any further suggestion, I am open to try out everything.

**Comment by Barabba11** [comment]
You need to understand who is using now the port 80, stop red node for a while and check if port 80 is open, for this you need a tool on another pc, to be sure, like tcptest tool.for windows. If nothing is open then start more red and check again, if not working check why, you need to NAT to the same port the this module is listening, as our friend suggested here the example it should be 8080.
If there is something else already then you need to move to another port, search how, you will see UI after opening that port. Alexa want port 80, point. I'm not sure that after you find devices you can disable port 80, in my opinion it will not work if you do it.
This is a direct way to drive your items even without internet, they should be in the same LAN domain, for example the same WiFi, be really sure it is like this.
If you have in your device both cable and WiFi be sure to use only one of these interfaces, check in your router (DHCP) that the device you are using and Alexa has both an IP address assigned

**Comment by BlackRedM** [comment]
it's a pity no one here writes the answer...
1. sudo iptables -t nat -L --line-numbers (if it doesn't say anything about 8083/your port, then it's clear that it doesn't work)
2. sudo iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT
3. sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8083
4. For the Node-Red Adapter insert port 8083 at the "Amazon Echo Hub" node and click deploy in the upper right corner and it works or it finds the devices and it is green.
5. Another time sudo iptables -t nat -L --line-numbers (see if it says 8083, if it does then it should work) 
Now the whole thing must be saved permanently if the device is restarted
1. sudo apt-get install iptables-persistent
2. sudo bash -c "iptables-save > /etc/iptables/rules"  | or service iptables save |  if the 1 does not work, in any case the problem is the saving 

It does not work with most of them because it is not saved permanently and the port forwarding is gone again at the next restart. Therefore save the iptable or port forwarding at the end.

----------------------------------------------------------------------------------------------------------------------------------------------

Ich finde es schade, dass keiner hier die Lösung schreibt...
1. sudo iptables -t nat -L --line-numbers (wenn hier nichts von 8083/euren Port steht, dann ist es klar, dass es nicht geht)
2. sudo iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT
3. sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8083
4. Bei dem Node-Red Adapter bei dem "Amazon Echo Hub" Node den Port 8083 einfügen und oben rechts deploy klicken und es funktioniert bzw. er findet nun die Geräte und es ist grün.
5. Nochmal sudo iptables -t nat -L --line-numbers (gucken ob da nun 8083 steht, wenn ja dann sollte es gehen) 
Nun muss das Ganze noch dauerhaft gespeichert werden falls das Gerät neugestartet wird
1. sudo apt-get install iptables-persistent
2. sudo bash -c "iptables-save > /etc/iptables/rules"      | oder  service iptables save falls das 1 nicht gehen sollte, auf jeden Fall ist die Speicherung das Problem 

Es geht bei den meisten nicht da es so nicht dauerhaft gespeichert wird und beim nächsten Neustart die Portweiterleitung wieder weg ist. Deshalb am Ende das iptable bzw. die Portweiterleitung speichern.

**Comment by czacherl** [comment]
Sorry for not getting back to my own issue for so long, I was engaged in other things.
@BlackRedM Thanks for the input. After adding the redirect to the iptables, I am not able to access the UI neither of the ccu nor the Node-Red via my browser any more.
So, I have tried to change the "Amazon Echo Hub" node before and add the redirect afterwards. Still Alexa is not finding any new device
After a reboot of the ccu, I can access both the ccu UI as well as the node-red.
I guess I will give up at this point, as it seems to me, that this is not working with a pre-manufactured ccu by homematic
Thanks for your help.

----

Es tut mir leid, dass ich mich so spät zurück melde, Ich war anderseitig eingespannt.
@BlackRedM Danke für dein Feedback. Nachdem ich den redirect in iptables eingetragen habe, kann ich nicht mehr auf die UI der ccu oder von node-red zugreifen.
Also habe ich versucht die "Amazon Echo Hub" node vor der iptables Änderung anzupassen und dann den redirect einzufügen. Alexa findet trotz allem kein neues Gerät.
Nach einem Reboot der CCU kann ich wieder auf die UIs zugreifen.
Ich schätze, ich gebe an dieser Stelle auf, es scheint, als würde ich nicht mit der vorinstallierten CCU von Homematic weiter kommen.
Vielen Dank für deine Hilfe

**Comment by aseedorf** [comment]
unfortunatly this cannot work with CCU3 / Homematic: Port 80 is used by the config-site of Homematic.
So as port 80 is already in use by the webservice, there is no (easy) way to use this node.
It is better to use a raspberry-pi and install node-red with this node.

**Comment by czacherl** [comment]
Thanks for your input and feedback everybody. It seems, that I will change my setup to a new CCU.
