### ISSUE TITLE
amazon-echo-hub-node issues with auto discovery and docker ?

### ISSUE THREAD

**Issue by glennpierce** [datech/node-red-contrib-amazon-echo#178]
I am trying to run nodered in docker and get device detection to work.
Following the examples I understand that I am to use network_mode: host

amazon-echo-hub-node is set to port 80 
(It would be nice to be able to set the ip address here for people with multiple nics. I had to add the interface/ip to the http server in the js code)

My main issue and one I don't understand how others got around is this.

amazon-echo-hub-node when is runs a ssdp server will use port 1900 
and as we use host networking that port will be used on the host machine

I get EADDRINUSE 0.0.0.0:1900

because docker itself uses that port 

ie

sudo netstat -tulpn | grep :1900
udp        0      0 0.0.0.0:1900            0.0.0.0:*                    2075/docker-proxy   
udp6       0      0 :::1900                 :::*                                2083/docker-proxy

How have people got around this ?

Thanks

**Comment by pauly7300** [comment]
I can't figure this one out either at the moment.  My problem goes 1 level deeper.  I'm running the NR docker on a NAS machine.  I can't figure out how to start NR in the docker container running as root in order to even try to deploy the node to listen on Port 80.  I get permission denied, which I've read is because i'm not running as Root.  I just don't have enough experience with docker to figure this one out atm.

**Comment by datech** [comment]
Related to issue #200
