### ISSUE TITLE
Make Amazon Echo Hub port configurable

### ISSUE THREAD

**Issue by dynamicdave1515** [datech/node-red-contrib-amazon-echo#2]
I should have said... I have Alexa local and Alexa home nodes installed in NR.
Do I need to remove these nodes for your Amazon node to function correctly???

**Comment by datech** [comment]
No, you don't need to uninstall them. The node is running a hub on port 80, but in your case it cannot be started on this port. 

Could you share more info about your setup? 

- Is this a Home Assistanse intance or separate Node-Red. 
- Which is the user you used to run Node-Red. Please, note that in order to start a process on port under 1024 (port 80 in our case) you will need root access

**Comment by dynamicdave1515** [comment]
Hi,
thanks for getting back to me.

I'm not using Home Assistant just Node-RED (v0.20.0-beta.2) running on a Raspberry Pi 3+

I'm logged into the Pi as user "pi", so I assume I'm running the NR instance as user "pi".

Alexa-local and Alexa-home run without any problems on my set-up, so I assume they must be using a different communication method.

Kind regards from David.

**Comment by dynamicdave1515** [comment]
Found this discussion on Discourse about using Port 80 without being 'root'

https://discourse.nodered.org/t/node-red-on-port-80/2211/4?u=dynamicdave

**Comment by datech** [comment]
Hello David,

Echo Dot 3 gen is trying to connect to 80 even you send to it that the hub is running on a different port. Alexa-local is using ports greater that 1024 that’s why root access is not needed, but because of that is not working with newer Echo devices.

I haven’t  tried the solution proposed on Discourse and I’d be interested to know if it is working

**Comment by dynamicdave1515** [comment]
Thanks for your swift response.

I have an Echo Dot gen-2 and one of my friends has a gen-3 version.
At the moment I can only test your node with Echo Dot gen-2.
Your response doesn't seem to make sense for my situation (for an Echo Dot gen-2) unless your node-hub is listening on port-80.

**Comment by dynamicdave1515** [comment]
That sounds like a good idea to make the port address configurable.

Have you thought about sharing your node/package on Node-RED Discourse as they have a category called "Share your nodes" ??

I'm sure you would get quite a bit of valuable feedback by doing that.

Kind regards from David.

**Comment by datech** [comment]
Thanks for pointing me out "Share your nodes"

I will make the port configurable in the next version and I leave this issue open until it is released.
