### ISSUE TITLE
Interaction with Alexa 

### ISSUE THREAD

**Issue by GordonTraveler** [datech/node-red-contrib-amazon-echo#51]
Hello. 

It is not really an issue... but it's connected with the node-red-contrib-amazon-echo.

First of all... great job! I used the local version before without color change possibility. Now I can even change the color. Awesome!
But it also gives me headache. I have RGBW leds, which I control in different ways. Via Web, via Alexa, partly automatic. The thing is now that - if I change the color via web form - then Alexa does not know about the color change and has still its own settings. 
Is there any way that I give a feedback to Alexa that the color setting changed (not via voice control of course). 

Also... is there now a way to give feedback after a voice command. Alexa says alway "OK" for any command. Regardles if the command was successfull or not. I would like to 'tell Alexa' what to say. Is it possible?

**Comment by verjus** [comment]
The software keeps track of the state of each light. Of course, if the state of a light is modified, the software will not know about it, as you describe. To address this, the author defined an input node which can be used to send a message updating the state. Look at the wiki for an example. As the author programmed it, the state will be updated but the change will also be propagated if the state is different. This behavior did not suit my needs, so I've modified it in a [fork](https://github.com/verjus/node-red-contrib-amazon-echo) To update the state, you simply send a json payload, for example: {"on":true, "bri":11, "nodeid": "Hue_5"} to the input node. Make sure to leave the topic empty. If you want to pass-through and change the state, simply add a topic. For example, topic "Brightness" will change the brightness and update the rest of the state. Other topics are State, Color, Temperature. 
Note that i've made other modifications, such as allowing for a friendly name for each device instead of a UUID. Hope this helps.

**Comment by datech** [comment]
"Is there any way that I give a feedback to Alexa that the color setting changed (not via voice control of course)."

Yes, you can send input payload to Amazon Echo Hub. You may check help on the node for the full list of supported attributes.

"Alexa says alway "OK" for any command. Regardles if the command was successfull or not. I would like to 'tell Alexa' what to say. Is it possible?"

No, I don't have control over the Alexa responses.
