### ISSUE TITLE
Enhancement: IP of source Echo needed

### ISSUE THREAD

**Issue by HanSolo72** [datech/node-red-contrib-amazon-echo#59]
##### SUMMARY

I need to identify the Echo Dot from where the voice command was sent. As example, when I say "Lights on" then when I say this to my Echo in the Kitchen the lights in the kitchen should go on, but when I say "Lights on" in the bedroom, the lights there should go on.
##### ECHO DEVICES
2Echo Dot 2nd generation

##### MODULE VERSION

```paste below
0.1.8
```

##### CONFIGURATION

```paste below

```

##### CONSOLE OUTPUT

```paste below

```

**Comment by Barabba11** [comment]
I agree with request, very important. I suggest to filter it by Echo's IP address, on the configuration window of every devicw there can be a field to specify the IP address of the Echo which can recognize it and drive it. Other Echo will not see this device so never discover too. If we need a device could be driven by 2 echos simply double the device node and assign it different IP. We just will need one HUB

**Comment by datech** [comment]
It is duplicate to #22

Usually one of Echo devices is acting as master, and all requests are routed through it. So, there is no way to differentiate which Echo device initiated the connection to Amazon Echo Hub. That's why it doesn't make sense to implement it.

**Comment by Barabba11** [comment]
As I wrote in other post, chances are with different Amazon accounts there will not be slaves Echo devices

**Comment by manmac2** [comment]
Hi, would like to give it a try with different accounts. does anyone know how I would then be able to get the ip adress to check if it would work that way?

**Comment by datech** [comment]
As part of #67 Alexa master device IP is included in payload output

Released in v0.1.9

**Comment by manmac2** [comment]
Hmmm - I have the version 0.1.9 running but do not see any device IP. Is there something which has to be configured?

```
msg : Object
object
on: false
bri: 254
hue: 0
sat: 254
ct: 199
colormode: "ct"
rgb: array[3]
0: 255
1: 0
2: 0
payload: "off"
deviceid: "df9293af02dd6"
topic: ""
_msgid: "f171f278.8aa1c"
```

**Comment by datech** [comment]
It looks like the version is not installed correctly in your Node-Red. I've just tested it with the published v0.1.9.

```
Welcome to Node-RED
===================

6 Oct 13:48:49 - [info] Node-RED version: v0.20.7
6 Oct 13:48:49 - [info] Node.js  version: v11.9.0
6 Oct 13:48:49 - [info] Linux 4.15.0-29-generic x64 LE
6 Oct 13:48:49 - [info] Loading palette nodes
6 Oct 13:48:49 - [debug] Module: node-red-contrib-amazon-echo 0.1.9
```

Here is how the payload should look like:

```
{
   "on":true,
   "bri":254,
   "hue":0,
   "sat":254,
   "ct":199,
   "colormode":"ct",
   "meta":{
      "insert":{
         "by":"alexa",
         "details":{
            "ip":"::ffff:192.168.1.15",
            "user_agent":"Dalvik/2.1.0 (Linux; U; Android 7.1.2; AEODN Build/NS6533)",
            "date":"2019-10-06T13:52:53.099Z"
         }
      },
      "input":{
         "on":true
      },
      "changes":{
         "on":false
      }
   },
   "rgb":[
      255,
      0,
      0
   ],
   "percentage":100,
   "payload":"on",
   "deviceid":"bda45e55920b2",
   "topic":"",
   "_msgid":"812b576d.02b518"
}
```

**Comment by manmac2** [comment]
thx, I have done the update again and now it‘s working perfectly. beside setting up a second google account which is not that much effort the convenience is great.

**Comment by Barabba11** [comment]
@manmac2 I've installed 1.9 on Windows and hopefully tomorrow on RPi, I don't see on device the option to specify the IP address so how you manage to distinguish commands between Echo? Mabe you filter the object when it comes out from device, and you trash if the command become from the not desidered Echo, but now you are in the situation where both Echoes recognizes the same device yes? So if you give a simple name, for example "curtains" you can't use the same name on different room yes? Because if you will do it both echo will activate the curtains in the other room..

**Comment by manmac2** [comment]
here all the steps I have had to go, hope that helps. ;) 
My setup consists of a debian server with node-red and iobroker including two alexa dots which are linked to different amazon accounts (as mentioned above otherwise there wouldn‘t be a difference in the IP adress)

- first make sure you have the latest version not only of node-red but also of the node-red-contrib-amazon-echo. On the top right you should see a menu enty like “edit palette”, check there if you have installed a version 0.1.9 or higher
- assign a fix IP adresses on your router for every alexa dot
- within node-red use the node “amazon alexa hub”, connect it to an “amazon echo device” node and name it “test”, and connect this with an debug node (enable show full message)
- deploy the flow
- open the debug tab on the right
- assign every alexa dot to a different amazon account
- search on every dot for new devices -  the device test should show up - no further configuration should be necessary
- call alexa to switch on test and check out the message in the debug window. It should look like this:
```
object
   on: false
   bri: 254
   hue: 0
   sat: 254
   ct: 199
   colormode: "ct"
   meta: object
      insert: object
      by: "alexa"
      details: object
         ip: "::ffff:192.168.1.19”
         ...
...
```
- when you repeat that on the other alexa devices you get all the ip strings 
- with the given strings you can configure a switch node (msg.meta.insert.details.ip == ::ffff:192.168.1.19) and trigger different automations with the same command by just calling a different alexa dot.

voila.

**Comment by Barabba11** [comment]
@manmac2 thank you, My goal is that every Echo discover only some devices, because I'm going to use devices with the same names in 2 different flows.
I need to know if it is enough to switch the packet between hub and device will be enough, or if the script of module is made in a way that even if I filter out packets going to device the hub will always comunicate the full list of devices to any Echo that is searching. I think only @datech knows that
Anyway thank you

**Comment by manmac2** [comment]
You are welcome, I think I have misunderstood your request. To be honest I am not aware if there is a possibility to do that beside setting up two different node-red instances and using your routers policies to route the traffic depending on the device. May I ask why it is not possible to use different names for the devices?

**Comment by Barabba11** [comment]
You may create as many NR you'd like.. but devices will be discovered by all of them if the Echos and NRs will be int he same broadcast domain. At home I have one Wi-Fi, so the same domain.
