### ISSUE TITLE
WHITE and BLACK not recognised...

### ISSUE THREAD

**Issue by scargill** [datech/node-red-contrib-amazon-echo#61]
I'm using node-red-contrib-amazon-echo with a generation 3 ECHO - and FINALLY gotten to grips with handling RGB lighting. However, the DIRECT OUTPUT from the ECHO DEVICE NODE - I can see colour changes in the RGB array and in the other outputs - but if I say "ECHO SET MY BENCH LIGHT TO WHITE" or "ECHO SET MY BENCH LIGHT TO BLACK" there is a response, but no colour change - BLACK isnt an issue as OFF will do- but WHITE is a problem....

SELECTING WHITE - the output mode changes from HS to CS (can't we just force it to RGB - I cant find a way to do that either). BLACK sets it back to HS - but neither make any change to the colour.

I'm using RGB (5v serial) LEDS - not that this should affect anything - the output I'm talking about is from the device node.
HELP

**Comment by datech** [comment]
Can you provide any debug info from the console?

**Comment by datech** [comment]
@scargill 
It is expected behavior to switch color mode to CT when color is changed to white, cool white, warm white, and so on.

If you add a JavaScript node that updates the rgb based on ct value might look like a resolution.

**Comment by cymplecy** [comment]
I've added this code to my copy to adjust rgb output to cope with black, white, warmwhite and coolwhite
```
    if (msg.colormode == "hs" && msg.hue == 0 && msg.sat == 0) { // black
        msg.rgb = [0, 0, 0];
    }
    if (msg.colormode == "ct" && msg.hue == 0 && msg.sat == 254 && msg.ct == 284) { // white
        msg.rgb = [255, 255, 255];
    }
    if (msg.colormode == "ct" && msg.hue == 0 && msg.sat == 254 && msg.ct == 383) { // warm white
        msg.rgb = [253, 245, 230]; //HTML OldLace 
    }
    if (msg.colormode == "ct" && msg.hue == 0 && msg.sat == 254 && msg.ct == 199) { // cool white
        msg.rgb = [248, 248, 254]; //HTML GhostWhite
    }

```

I can do a PR if your happy for me to do so

**Comment by datech** [comment]
Thanks, @cymplecy. I would prefer to include an external npm that will do this for us, like this one: https://www.npmjs.com/package/color-temp

I will try to provide it in the next few days

**Comment by Barabba11** [comment]
Just a curiosity, is && a bitwise operator? Are you changing the message contents inside the if comparison?
I always use only & when I'm making comparison

**Comment by cymplecy** [comment]
Javascript uses single for bitwise and double for logical
https://www.w3schools.com/js/js_comparisons.asp
https://www.w3schools.com/js/js_bitwise.asp

**Comment by Barabba11** [comment]
Thanks, I always used double signs as I came from Arduino code, but once I lost different hours to understand what was wrong on a code, and someone suggested me to put the expression under () and use only &. For example if (test1===true) & (test2>1)

**Comment by datech** [comment]
Black is supported in the color mode set to **ct**. (colormode: 'ct') and all types of white are supported in the color mode set to **hs**.

Support of RGB input was added in v0.1.10, so it allows us to workaround this issue if needed.

**Comment by cymplecy** [comment]
:)
I don't understand why this issue has been closed if no code changes have been applied to address the issue

**Comment by datech** [comment]
I've closed it because now we can implement a workaround on the flow level. 
The current logic is:
- RGB colors like black, red, and so on are supported only in HS mode;
- White colors are supported only in CT mode;

The hub is handling Alexa commands correctly. 
When you ask Alexa to set the color to black, the hub will respond with:
```
{
...
   "rgb":[
      254,
      254,
      254
   ],
   "colormode":"hs",
   "meta":{
...
      "input":{
         "hue":0,
         "sat":0
      }
   }
....
}

```

Note the input coming from Alexa:
```
      "input":{
         "hue":0,
         "sat":0
      }
```

Based on this input, the hub is changing the color mode from CR to HS. 
At the same time, I don't see any change in the Alexa app, and the color there is still set to white, which should be considered as a bug the in app, not in the hub.

Version 0.1.10 has introduced support of RGB colors in the input, which allows us to implement some workarounds for such issues. For example, when you ask Alexa to set the color to black, you can change the color to red instead.

I think that the app will always default to white color if the color you set is not in the list of RGB colors shown in the app.
